title: Lets Go Animals
author: mgchitwood2
email: mgchitwood2@github.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about animals and it is finals week but besides that, 
  enjoy these animals because we need them.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
